"""add embedding column to chunks

Revision ID: 00ef72b80a7a
Revises: 3f0f9def5516
Create Date: 2026-06-18 08:05:22.780936

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ef72b80a7a'
down_revision: Union[str, Sequence[str], None] = '3f0f9def5516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'chunks',
    sa.Column(
        'embedding',
        Vector(384),
        nullable=True
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
