"""add chunk positions

Revision ID: 53f1140934c5
Revises: 00ef72b80a7a
Create Date: 2026-06-21 09:19:54.920365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f1140934c5'
down_revision: Union[str, Sequence[str], None] = '00ef72b80a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('start_char', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('end_char', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'end_char')
    op.drop_column('chunks', 'start_char')
    # ### end Alembic commands ###
